### PR TITLE
Drop Python 2 support and compatibility code

### PR DESCRIPTION
**Pull request by jelmer**
This drops support for Python 2, and removes associated compatibility code.

I did this work for a private project (to get rid of the six dependency), but
figured it might be useful upstream as well (since Python 2 is EOL).

### CODE REVIEW

**Comment by jelmer** [comment]
ping @DiffSk

alternatively, anything I can do to help with maintenance?

**Comment by jelmer** [comment]
ping @robdennis

alternatively, anything I can do to help with maintenance?

**Comment by a-detiste** [comment]
@jelmer 

Should we consider using your patch for the Debian package ?

**Comment by a-detiste** [comment]
`mock` should be removed too

.github/workflows/python-test.yml

```
-pip install pytest coverage pytest-cov mock
+pip install pytest coverage pytest-cov
```

**Comment by jelmer** [comment]
Hey @EliAndrewC , @robdennis , anything we can do to help with the maintenance for the project / help get outstanding PRs / issues resolved?

**Comment by EliAndrewC** [comment]
I apologize for the delayed response.

Both @robdennis and I are the current maintainers, but we've found we lack the time to review and publish new versions of configobj.  In the spirit of good stewardship, we'd be happy to hand over maintainer status to people who are interested in making these kinds of changes, especially people like @jelmer who have already put in the effort to make PRs.

@jelmer , is taking over as maintainer of the project something that you feel you have the bandwidth for?  Either solo, or alongside others such as @yegorich who have also filed PRs and inquired about the status of the project?  (The last person we tried to hand the project off to had their own life issues arise and were not able to end up taking over, so we'd feel a little better granting this access to multiple people, but the most important thing is to unblock all of these PRs by giving **someone** the access needed to review and accept them.)

**Comment by jelmer** [comment]
> I apologize for the delayed response.
> 
> Both @robdennis and I are the current maintainers, but we've found we lack the time to review and publish new versions of configobj. In the spirit of good stewardship, we'd be happy to hand over maintainer status to people who are interested in making these kinds of changes, especially people like @jelmer who have already put in the effort to make PRs.
> 
> @jelmer , is taking over as maintainer of the project something that you feel you have the bandwidth for? Either solo, or alongside others such as @yegorich who have also filed PRs and inquired about the status of the project? (The last person we tried to hand the project off to had their own life issues arise and were not able to end up taking over, so we'd feel a little better granting this access to multiple people, but the most important thing is to unblock all of these PRs by giving **someone** the access needed to review and accept them.)

Thanks for the reply, @EliAndrewC - yeah, I would be interested in that. I do have bandwidth but I agree having multiple maintainers would be a good idea either way.

**Comment by yegorich** [comment]
I am also interested in helping to maintain this project. Though, I don't have that much bandwidth.

**Comment by jelmer** [comment]
@EliAndrewC / @robdennis thanks for adding me to the project; what's the current philosophy around the master vs release branches? They appear to have diverged, and afaict I can't merge anything into release.

**Comment by robdennis** [comment]
> @EliAndrewC / @robdennis thanks for adding me to the project; what's the current philosophy around the master vs release branches? They appear to have diverged, and afaict I can't merge anything into release.

How I found the project when I last had the cycles to look at it: https://github.com/DiffSK/configobj/issues/213

At the bottom of this thread, I update how I found the state of the two different branches, specifically, the tooling changes introduced (but not AFAICT, fully landed) did not leave me in a place where I felt like I could execute on getting a release out. One of my last comments notes what I though I could do, which was do something targeted off of the last branch I could understand.

This issue describes the last thing I did: https://github.com/DiffSK/configobj/issues/223

my overall philosophy for the project is that there are so many legacy consumers that it’s difficult to imagine anything transformative being done, but also me and Eli are too old to keep up with what idiomatic open source is these days so we’re hoping someone else will.

can you let me know your PYPI username and I can give you credits over there?

**Comment by jelmer** [comment]
Thanks for the pointers, much appreciated.

> can you let me know your PYPI username and I can give you credits over there?

I'm "jelmer" on pypi.

**Comment by robdennis** [comment]
Invite sent, my understanding is that two factor authentication is required
these days, at least for this project due to its legacy nature. Mentioning
that in case there’s unforeseen issues.

**Comment by jelmer** [comment]
Hi @robdennis ,

I've merged this branch and the DoS PR into 5.0.x, and merged the recent 5.0.x changes into master as well - it'd be good to do another release. Is there any chance you could either give me access to the ``release`` branch or release a ``5.0.9``?

It would also be great if (now that there are github actions) we could require CI to pass for any merges.

**Comment by robdennis** [comment]
Hi @jelmer,

I had down that you had enough permissions to manage whatever you need to here and on pypi. I just bumped you up to admin level from maintain and hopefully that will give you whatever you need.

My ideal end state is that I'm not in the critical path for anything, since I'm unlikely to see any github emails or other notifications.

**Comment by jelmer** [comment]
Thanks, @robdennis ! I've just pushed out 5.0.9.

**Pull request merged**
